env:
  es6: true
  node: true
plugins:
- import
extends:
- eslint:recommended
- plugin:import/recommended
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  arrow-parens:
  - error
  - as-needed
  capitalized-comments:
  - error
  - always
  - {ignoreConsecutiveComments: true}
  curly:
  - error
  - multi-line
  - consistent
  dot-location:
  - error
  - property
  eqeqeq:
  - error
  - always
  - {null: ignore}
  generator-star-spacing:
  - error
  - {before: false, after: true}
  indent:
  - error
  - 2
  - {flatTernaryExpressions: true}
  object-curly-spacing:
  - error
  - always
  operator-linebreak:
  - error
  - before
  - overrides:
      '=': after
      '+=': after
      '-=': after
      '*=': after
      '/=': after
      '%=': after
      '**=': after
      '<<=': after
      '>>=': after
      '>>>=': after
      '&=': after
      '^=': after
      '|=': after
  padded-blocks:
  - error
  - {blocks: never, classes: never, switches: never}
  prefer-destructuring:
  - error
  - {VariableDeclarator: {array: false, object: true}}
  quote-props:
  - error
  - as-needed
  semi:
  - error
  - always
  space-before-function-paren:
  - error
  - {anonymous: always, named: never, asyncArrow: always}
  import/order:
  - error
  - {newlines-between: never}
  array-bracket-spacing: error
  array-callback-return: error
  arrow-body-style: error
  arrow-spacing: error
  block-spacing: error
  brace-style: error
  camelcase: error
  comma-spacing: error
  computed-property-spacing: error
  dot-notation: error
  func-call-spacing: error
  key-spacing: error
  keyword-spacing: error
  max-len: error
  no-array-constructor: error
  no-caller: error
  no-cond-assign: off
  no-control-regex: off
  no-eval: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-implied-eval: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-proto: error
  no-return-await: error
  no-throw-literal: error
  no-undefined: error
  no-unneeded-ternary: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-whitespace-before-property: error
  no-with: error
  no-var: error
  object-shorthand: error
  operator-assignment: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-numeric-literals: error
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  rest-spread-spacing: error
  semi-spacing: error
  semi-style: error
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  strict: error
  template-curly-spacing: error
  template-tag-spacing: error
  yield-star-spacing: error
  import/extensions: error
  import/first: error
  import/newline-after-import: error
  import/no-extraneous-dependencies: error
  import/unambiguous: off
  # The below rules currently have no effect; they're left over from when I
  # played with extending other configs.
  consistent-return: off
  default-case: off
  function-paren-newline: off
  no-confusing-arrow: off
  no-lonely-if: off
  no-mixed-operators: off
  no-multi-assign: off
  no-nested-ternary: off
  no-param-reassign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-return-assign: off
  no-sequences: off
  no-shadow: off
  no-underscore-dangle: off
  no-unused-expressions: off
  no-use-before-define: off
  no-void: off
  one-var: off
  one-var-declaration-per-line: off
  prefer-spread: off
  prefer-template: off
  quotes: off
  import/prefer-default-export: off
